<body>
<?php

?>

<div class="container-fluid pl-0 pr-0 bg-img clearfix parallax-window2" data-parallax="scroll" data-image-src="<?=RUTAS_APP['ruta_img']?>images/banner.jpg">

  
  <div class="container">
    <div class="fh5co-banner-text-box col-md-6">
      <div class="quote-box pl-5 pr-5 wow bounceInRight">
        <h2> MARCA <br><span>LIDER EN NUTRICION</span> </h2>
      </div>
      
      <a href="<?= BASE_URL.'index/login' ?>" class="btn text-uppercase btn-outline-danger btn-lg mr-3 mb-3 wow bounceInUp">Iniciar Sesion</a> <a href="<?= BASE_URL.'index/formulario' ?>" class="btn text-uppercase btn-outline-danger btn-lg mb-3 wow bounceInDown"> Ir a formulario</a> </div>
      
  </div>
  
</div>
<div class="container-fluid fh5co-network">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h4 class="wow bounceInUp" id="network">FOR NETWORK</h4>
        <h2 class="wow bounceInRight">MEMBERS</h2>
        <hr />
        <h5 class="wow bounceInLeft">NETWORK SUMMER 2017</h5>
        <p class="wow bounceInDown">The lowdown on Blood Flow Restriction training ? FREE CEC/CPD ? ?Let's compare ?Raw Vs Cooked ? Building Ab, Core &amp; Pelvic strength ? Get? clients short-term wins from long-term goals ? So you want to operate multiple clubs? + LOADS MORE</p>
      </div>
      <div class="col-md-6">
        <figure class="wow bounceInDown"> <img src="<?= RUTAS_APP['ruta_img'] ?>images/about-img.jpg" alt="gym" class="img-fluid" /> </figure>
      </div>
    </div>
  </div>
</div>
<div id="about-us" class="container-fluid fh5co-about-us pl-0 pr-0 parallax-window" data-parallax="scroll" data-image-src="images/about-us-bg.jpg">
  <div class="container">
    <div class="col-sm-6 offset-sm-6">
      <h2 class="wow bounceInLeft" data-wow-delay=".25s">ABOUT US</h2>
      <hr/>
      <p class="wow bounceInRight" data-wow-delay=".25s">Trainers, athletes and serious clients alike are looking for the toughest, most brutally productive training techniques to spice up their workouts and provide a truly unique challenge for their body and mind. Think: one-arm push-ups, pistols, pull-ups, handstands, hanging levers and the like! If you want toeither for </p>
      <a class="btn btn-lg btn-outline-danger d-inline-block text-center mx-auto wow bounceInDown">Learn More</a> </div>
  </div>
</div>
<div class="container-fluid fh5co-content-box">
  <div class="container">
    <div class="row">
      <div class="col-md-5 pr-0"><img src="<?= RUTAS_APP['ruta_img']?>images/rode-gym.jpg" alt="gym" class="img-fluid wow bounceInLeft" /> </div>
      <div class="col-md-7 pl-0">
        <div class="wow bounceInRight" data-wow-delay=".25s">
          <div class="card-img-overlay">
            <p>Great weekend, met lots of cool people and took away quite a bit. Thank you for the experience, and to you and your professional team for 
              making things seem </p>
          </div>
          <img src="<?= RUTAS_APP['ruta_img']?>images/gym-girls.jpg" alt="girls in gym" class="img-fluid" /> </div>
      </div>
    </div>

 
  </div>
</div>
<footer class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-md-3 footer1 d-flex wow bounceInLeft" data-wow-delay=".25s">
        <div class="d-flex flex-wrap align-content-center"> <a href="#"><img src="<?= RUTAS_APP['ruta_img']?>images/logo.png" alt="logo" /></a>
          <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo
            dolor. Ae</p>
          <p>&copy; 2018 Foxpro. All rights reserved.<br> Design by <a href="https://freehtml5.co" target="_blank">FreeHTML5</a>.</p>
        </div>
      </div>

      <div class="col-md-3 footer3 wow bounceInRight" data-wow-delay=".25s">
        <h5>ADDRESS</h5>
        <p>Lorem ipsum dolor sit 
          amet, consectetuer adipiscing elit.</p>
        <h5>PHONE</h5>
        <p>253232323232</p>
        <h5>EMAIL</h5>
        <p>email@example.com</p>
        <div class="social-links">
          <ul class="nav nav-item">
            <li><a href="https://www.facebook.com/fh5co" class="btn btn-secondary mr-1 mb-2"><img src="<?= RUTAS_APP['ruta_img']?>images/facebook.png" alt="facebook" /></a></li>
            <li><a href="#"  class="btn btn-secondary mr-1 ml-1 mb-2"><img src="<?= RUTAS_APP['ruta_img']?>images/facebook.png" alt="facebook" /></a></li>
            <li><a href="#"  class="btn btn-secondary mr-1 ml-1 mb-2"><img src="<?= RUTAS_APP['ruta_img']?>images/facebook.png" alt="facebook" /></a></li>
            <li><a href="#"  class="btn btn-secondary ml-1 mb-2"><img src="<?= RUTAS_APP['ruta_img']?>images/facebook.png" alt="facebook" /></a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

<!-- Optional JavaScript --> 
<!-- jQuery first, then Bootstrap JS, ... -->


<script src="<?= RUTAS_APP['ruta_js']?>bootstrap.min.js"></script>
<script src="<?= RUTAS_APP['ruta_js']?>parallax.js"></script>
<script src="<?= RUTAS_APP['ruta_js']?>wow.js"></script>
<script src="<?= RUTAS_APP['ruta_js']?>main.js"></script>



</body>
</html>